continue Richard's PR #2
learningequality/kolibri-exercise-perseus-plugin pull request #3
Opened 2016-10-05 23:36 UTC by 66eli77

2016-10-20 21:10 UTC, indirectlylit requested changes
Hey - mind making a few quick updates to this?

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            console.log('PPPPPPP:::: ', this.passNum);
mind clearing out all the debugging code before we merge this in?

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/index.vue
> +  const ss = require('seededshuffle');
is this in package.json?

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +    <div id="answer-area-wrap">
whitespace cleanup below

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> -    </div>
looks like an unclosed `div` here?

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            const lastFiveAttempts = this.pastattempts.slice(0, this.passRatioM);
this variable should be renamed

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +      passNum: 4,
I think it would be much cleaner to implement `passNum` as a computed property rather than updating it in `attemptProgress`.

2016-10-20 21:10 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            this.$parent.$emit('checkanswer', this.correct, this.complete, this.firstAttempt, this.hinted);
Could you add a comment explaining what this line does?

Calling `this.$parent` is very unusual, let alone `this.$parent.$emit`.

2016-10-20 22:00 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/index.vue
> +  const ss = require('seededshuffle');
the question.json is a dummy json Richard created for testing, now we just use the real one from Jordan.
seededshuffle is a seeded randomize library. I use the user_id as the seed.

2016-10-20 22:02 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            console.log('PPPPPPP:::: ', this.passNum);
haha

2016-10-20 22:05 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            this.$parent.$emit('checkanswer', this.correct, this.complete, this.firstAttempt, this.hinted);
why Calling this.$parent is very unusual?

2016-10-20 22:09 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +      passNum: 4,
You cannot pass computed as props in Vue

2016-10-20 22:11 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/perseus.vue
> -    </div>
oops, the indentation isn't aligned. The div is closed.

2016-10-20 22:17 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            this.$parent.$emit('checkanswer', this.correct, this.complete, this.firstAttempt, this.hinted);
It's uncommon for a child component to directly reference the parent component. It goes against the composition rule of only communicating with events: https://vuejs.org/guide/components.html#Composing-Components

2016-10-20 22:18 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/index.vue
> +  const ss = require('seededshuffle');
I meant to say - has the `seededshuffle` library been added to the dependencies list (defined in this plugin's `package.json` file)?

2016-10-20 22:19 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +      passNum: 4,
of course you can - let's chat if there's confusion

2016-10-20 22:22 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +                </button>
we should use the core `icon-button` component for all buttons

2016-10-20 23:04 UTC, 66eli77 commented on exercise_perseus_render/assets/src/vue/index.vue
> +  const ss = require('seededshuffle');
good point, I should add it here instead of kolibri

2016-10-20 23:45 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            this.$parent.$emit('checkanswer', this.correct, this.complete, this.firstAttempt, this.hinted);
see related comment here: https://github.com/learningequality/kolibri/pull/565#discussion_r84396546

2016-10-21 02:19 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +            this.$emit('checkanswer', this.correct, this.complete, this.firstAttempt, this.hinted);
may have removed `$parent` by accident while we were talking?

2016-10-22 21:14 UTC, indirectlylit approved these changes
all right!

2016-10-22 21:14 UTC, merged