implement next content btn
learningequality/kolibri-exercise-perseus-plugin pull request #4
Opened 2016-10-23 07:56 UTC by 66eli77

2016-10-26 05:41 UTC, indirectlylit commented
hey - hope you're feeling a bit better!

Unfortunately (as mentioned in https://github.com/learningequality/kolibri/pull/604) this change would couple the Perseus renderer to the implementation details of the Learn plugin.

we'll probably need to use props (to enable/disabled a 'next content' button) and event-based communication (to communicate to the parent that a button was pressed)

let me know if you'd like to chat about this.

2016-10-26 20:08 UTC, 66eli77 commented
@indirectlylit that will be great, I need your help to understand how learn page works and implement to next-content feature in learn.

2016-10-27 13:53 UTC, indirectlylit requested changes
looks good! couple small changes

2016-10-27 13:53 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +  const actions = require('kolibri/coreVue/vuex/actions');
I just merged in this PR - https://github.com/learningequality/kolibri/pull/589

so this line will change to:

```javascript
const actions = require('kolibri.coreVue.vuex.actions');
```

2016-10-27 13:53 UTC, indirectlylit commented on exercise_perseus_render/assets/src/vue/perseus.vue
> +  const actions = require('kolibri/coreVue/vuex/actions');
maybe also better to call this variable `coreActions` ?

2016-10-27 20:41 UTC, merged